gravitino.exceptions.base.UnknownError
======================================

.. currentmodule:: gravitino.exceptions.base

.. autoexception:: UnknownError