gravitino.exceptions.base.CatalogNotInUseException
==================================================

.. currentmodule:: gravitino.exceptions.base

.. autoexception:: CatalogNotInUseException